server:
    port: 8080
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8888/eureka

spring:
    application:
        name: iogateway-service
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
                - AddResponseHeader=Access-Control-Allow-Origin, *
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: '*'
                        allowedHeaders: "*"
                        allowedMethods: "*"

io:
    security:
        jwt:
            secret: iodev